### ISSUE TITLE
Substrait crate fails to build on Windows in dependent project

### ISSUE THREAD

**Issue by andygrove** [substrait-io/substrait-rs#53]
We have added Substrait support to DataFusion now but cannot add it to the project workspace (see https://github.com/apache/arrow-datafusion/pull/4893) because Windows builds are failing due to a protoc error when building Substrait.

```
error: failed to run custom build command for `substrait v0.2.0`

Caused by:
  process didn't exit successfully: `D:\a\arrow-datafusion\arrow-datafusion\target\debug\build\substrait-a6509fbb99b47d6b\build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=FORCE_REBUILD

  --- stderr
  Error: "protobuf compilation failed: protoc failed: Missing input file.\r\n"
```

**Comment by mbrobbel** [comment]
Can you check if it also fails to build with the latest release (0.3.0)?

**Comment by andygrove** [comment]
> Can you check if it also fails to build with the latest release (0.3.0)?

Thanks. Yes, upgrading to 0.3 fixed it :tada:
